// Export LiDAR scan results to CSV-style text. Use Print to console or copy for external tools.
class RDF_LidarExport
{
    // CSV header line.
    static string GetCSVHeader()
    {
        return "index,hit,startX,startY,startZ,endX,endY,endZ,dirX,dirY,dirZ,hitPosX,hitPosY,hitPosZ,distance,colliderName";
    }

    // Format one sample as CSV row.
    static string SampleToCSVRow(RDF_LidarSample sample)
    {
        if (!sample) return "";
        string hitStr = "0";
        if (sample.m_Hit)
            hitStr = "1";
        vector s = sample.m_Start;
        vector e = sample.m_End;
        vector d = sample.m_Dir;
        vector h = sample.m_HitPos;
        string coll = sample.m_ColliderName;
        if (!coll)
            coll = "";
        string row = sample.m_Index.ToString() + "," + hitStr + ",";
        row = row + s[0].ToString() + "," + s[1].ToString() + "," + s[2].ToString() + ",";
        row = row + e[0].ToString() + "," + e[1].ToString() + "," + e[2].ToString() + ",";
        row = row + d[0].ToString() + "," + d[1].ToString() + "," + d[2].ToString() + ",";
        row = row + h[0].ToString() + "," + h[1].ToString() + "," + h[2].ToString() + ",";
        row = row + sample.m_Distance.ToString() + ",\"" + coll + "\"";
        return row;
    }

    // Print full CSV (header + all rows) to console. Copy from log for external files.
    static void PrintCSVToConsole(array<ref RDF_LidarSample> samples)
    {
        if (!samples) return;
        Print(RDF_LidarExport.GetCSVHeader());
        for (int i = 0; i < samples.Count(); i++)
        {
            RDF_LidarSample s = samples.Get(i);
            if (s)
                Print(RDF_LidarExport.SampleToCSVRow(s));
        }
    }

    // Export last scan from a visualizer to console (CSV).
    static void ExportLastScanToConsole(RDF_LidarVisualizer visualizer)
    {
        if (!visualizer) return;
        ref array<ref RDF_LidarSample> samples = visualizer.GetLastSamples();
        RDF_LidarExport.PrintCSVToConsole(samples);
    }

    // Serialize samples to compact CSV string for network broadcast (see RFC in code comments).
    static string SamplesToCSV(array<ref RDF_LidarSample> samples)
    {
        if (!samples || samples.Count() == 0)
            return string.Empty;

        string csv = "";
        for (int i = 0; i < samples.Count(); i++)
        {
            RDF_LidarSample s = samples.Get(i);
            // Format: idx|hit|startX,startY,startZ|hitX,hitY,hitZ|dirX,dirY,dirZ|dist
            string hitStr = "0";
            if (s.m_Hit)
                hitStr = "1";
            string part = s.m_Index.ToString() + "|" + hitStr + "|";
            part = part + s.m_Start[0].ToString() + "," + s.m_Start[1].ToString() + "," + s.m_Start[2].ToString() + "|";
            part = part + s.m_HitPos[0].ToString() + "," + s.m_HitPos[1].ToString() + "," + s.m_HitPos[2].ToString() + "|";
            part = part + s.m_Dir[0].ToString() + "," + s.m_Dir[1].ToString() + "," + s.m_Dir[2].ToString() + "|";
            part = part + s.m_Distance.ToString();
            if (i < samples.Count() - 1)
                csv += part + ";";
            else
                csv += part;
        }
        return csv;
    }

    // Parse CSV string generated by SamplesToCSV back into samples.
    static array<ref RDF_LidarSample> ParseCSVToSamples(string csv)
    {
        array<ref RDF_LidarSample> outSamples = new array<ref RDF_LidarSample>();
        if (!csv || csv == string.Empty)
            return outSamples;

        array<string> parts = new array<string>();
        csv.Split(";", parts, false);
        foreach (string part : parts)
        {
            array<string> f = new array<string>();
            part.Split("|", f, false);
            if (f.Count() < 6)
                continue;

            int idx = f.Get(0).ToInt();
            bool hit = f.Get(1) == "1";

            array<string> vals = new array<string>();
            // start
            f.Get(2).Split(",", vals, false);
            vector start = Vector(vals.Get(0).ToFloat(), vals.Get(1).ToFloat(), vals.Get(2).ToFloat());
            vals.Clear();
            // hitPos
            f.Get(3).Split(",", vals, false);
            vector hitPos = Vector(vals.Get(0).ToFloat(), vals.Get(1).ToFloat(), vals.Get(2).ToFloat());
            vals.Clear();
            // dir
            f.Get(4).Split(",", vals, false);
            vector dir = Vector(vals.Get(0).ToFloat(), vals.Get(1).ToFloat(), vals.Get(2).ToFloat());
            vals.Clear();
            float dist = f.Get(5).ToFloat();

            RDF_LidarSample s = new RDF_LidarSample();
            s.m_Index = idx;
            s.m_Hit = hit;
            s.m_Start = start;
            s.m_HitPos = hitPos;
            s.m_Dir = dir;
            s.m_Distance = dist;

            outSamples.Insert(s);
        }

        return outSamples;
    }
}
