RDF_DemSurfManifestConf {
 m_sMagic "RDF_SURF_JSON_V1"
 m_sWorld "GM_Eden"
 m_fBoundsMinX -107.382
 m_fBoundsMinZ -100
 m_fBoundsMaxX 12800
 m_fBoundsMaxZ 12800
 m_fCellM 2
 m_iTileCells 32
 m_iTileCountX 202
 m_iTileCountZ 202
 m_sChunksDir "surf_chunks/"
}
