RDF_DemHeightManifestConf {
 m_sMagic "RDF_HEIGHT_JSON_V1"
 m_sWorld "GM_Cain"
 m_fBoundsMinX -100
 m_fBoundsMinZ -100
 m_fBoundsMaxX 12800
 m_fBoundsMaxZ 12827.8
 m_fCellM 2
 m_iTileCells 32
 m_iTileCountX 202
 m_iTileCountZ 202
 m_fYScale 0.1
 m_sChunksDir "height_chunks/"
}
