RDF_DemHeightManifestConf {
 m_sMagic "RDF_HEIGHT_JSON_V1"
 m_sWorld "GM_Arland"
 m_fBoundsMinX -129.755
 m_fBoundsMinZ -162.326
 m_fBoundsMaxX 4096
 m_fBoundsMaxZ 4096
 m_fCellM 2
 m_iTileCells 32
 m_iTileCountX 67
 m_iTileCountZ 67
 m_fYScale 0.1
 m_sChunksDir "height_chunks/"
}
