#!/usr/bin/env python3
"""Generate RDF_DemGuidIndex.c from DemData/**/*.conf.meta ResourceNames."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEM = ROOT / "DemData"
OUT = ROOT / "scripts" / "Game" / "RDF" / "DEM" / "Runtime" / "RDF_DemGuidIndex.c"

META_NAME_RE = re.compile(
    r'Name\s+"(\{[0-9A-Fa-f]+\})([^"]+)"'
)


def collect_entries() -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for meta in sorted(DEM.rglob("*.conf.meta")):
        text = meta.read_text(encoding="utf-8", errors="replace")
        match = META_NAME_RE.search(text)
        if not match:
            raise SystemExit(f"no ResourceName in {meta}")
        guid = match.group(1)
        path = match.group(2).replace("\\", "/")
        entries.append((path, f"{guid}{path}"))
    return entries


def main() -> None:
    entries = collect_entries()
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by tools/dem/rdf_dem_gen_guid_index.py — do not edit.")
    lines.append("// Maps DemData/... .conf paths to packed ResourceNames (CONFResourceClass).")
    lines.append("class RDF_DemGuidIndex")
    lines.append("{")
    lines.append("    protected static ref map<string, ResourceName> s_ByPath;")
    lines.append("")
    lines.append("    //--------------------------------------------------------------------------------------------")
    lines.append("    static ResourceName Lookup(string relativePath)")
    lines.append("    {")
    lines.append("        Ensure();")
    lines.append("        if (relativePath.IsEmpty() || !s_ByPath)")
    lines.append("            return ResourceName.Empty;")
    lines.append("        ResourceName rn;")
    lines.append("        if (!s_ByPath.Find(relativePath, rn))")
    lines.append("            return ResourceName.Empty;")
    lines.append("        return rn;")
    lines.append("    }")
    lines.append("")
    lines.append("    //--------------------------------------------------------------------------------------------")
    lines.append("    static bool Has(string relativePath)")
    lines.append("    {")
    lines.append("        ResourceName rn = Lookup(relativePath);")
    lines.append("        return !rn.IsEmpty();")
    lines.append("    }")
    lines.append("")
    lines.append("    //--------------------------------------------------------------------------------------------")
    lines.append("    protected static void Ensure()")
    lines.append("    {")
    lines.append("        if (s_ByPath)")
    lines.append("            return;")
    lines.append("        s_ByPath = new map<string, ResourceName>();")
    for path, resource_name in entries:
        lines.append(f'        s_ByPath.Set("{path}", "{resource_name}");')
    lines.append(f"        // {len(entries)} DemData CONF resources")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
